name: ideat
description: A new Flutter project.
publish_to: none
version: 1.1.0
environment:
  sdk: ">=2.15.0-116.0.dev <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  settings_ui: ^2.0.1
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
