# From https://github.com/mrchief/universal-changelog-action/blob/master/.github/workflows/changelog.yml

name: Auto Changelog

on:
  push:
    branches:
      - main
      - release

jobs:
  push:
    name: Push Container
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci: Release')"
    steps:
      - uses: actions/setup-python@v2.3.1

      - name: Checkout Code
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: "0"

      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - name: autochangelog-action
        id: ac
        uses: rubenfiszel/autochangelog-action@v0.16.0
        with:
          changelog_file: "./CHANGELOG.md"
          manifest_file: "./ideat/pubspec.yaml"
          dry_run: false
          issues_url_prefix: "https://github.com/timtimjnvr/ideat/issues"
          tag_prefix: "v"

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Update changelog and manifest"
          title: "ci: Release ${{ steps.ac.outputs.version }}"
          body: |
            Release v${{ steps.ac.outputs.version }}
          labels: autorelease
          branch: automatic-release-prs
          branch-suffix: short-commit-hash

      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ env.PULL_REQUEST_NUMBER }}"
          echo "Pull Request Number - ${{ steps.cpr.outputs.pr_number }}"
