name: Tag Release

on:
  push:
   tags: 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    env:
      changelog_file: "./CHANGELOG.md"

    steps:
      - uses: actions/checkout@v2

      # Note: This workflow uses the latest stable version of the Dart SDK.
      # You can specify other versions if desired, see documentation here:
      # https://github.com/dart-lang/setup-dart/blob/main/README.md
      # - uses: dart-lang/setup-dart@v1
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'
  
      - name: Install dependencies
        working-directory: "./ideat"
        run: flutter pub get

      - name: Build APK
        working-directory: "./ideat"
        run: flutter build apk --split-per-abi --target-platform android-arm64

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1

      - name: Use tag
        run: echo ${{steps.tag.outputs.tag}}

      - name: Extract version from tag
        uses: Amadevus/pwsh-script@v2.0.1
        id: getVersion
        with:
          script: '("${{steps.tag.outputs.tag}}").Split("v")[1]'
          
      - name: get changelog
        id: changelog
        shell: bash
        run: |
          changelog=$(echo "${{steps.getVersion.outputs.result}}" | xargs -I {} sed -n '/^#\s'"{}"'.*$/,/^#\s\([^[:space:]]\+\).*$/{//!p}' ${{ env.changelog_file }})
          echo $changelog
          changelog="${changelog//'%'/'%25'}"
          changelog="${changelog//$'\n'/'%0A'}"
          changelog="${changelog//$'\r'/'%0D'}"
          echo "::set-output name=changelog::$changelog"

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{steps.getVersion.outputs.result}}
          body: ${{ steps.changelog.outputs.changelog }}
          draft: false
          prerelease: false

      - name: Update release asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./ideat/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk"
          asset_name: ideat-arm64-v8a-release.apk
          asset_content_type: application/zip